---
- name: Add local admins and users
  hosts: windows_hosts
  gather_facts: no
  tasks:
    - name: copy powershell script
      ansible.windows.win_copy:
        src: ./addlocalUsers.ps1
        dest: C:\Users\greyTeam\Downloads\addlocalusers.ps1

    - name: run powershell script
      ansible.builtin.win_shell: |
        PowerShell -ExecutionPolicy Bypass -File C:\Users\greyTeam\Downloads\addlocalusers.ps1

    - name: delete script
      ansible.windows.win_file:
        path: C:\Users\greyTeam\Downloads\addlocalusers.ps1
        state: absent
