---

- name: Join Windows machines to the domain
  hosts: windows_hosts
  gather_facts: no
  tasks:
    - name: Join machine to domain
      win_domain_membership:
        dns_domain_name: "seneca.zoo"
        domain_admin_user: "seneca\\administrator"
        domain_admin_password: "z00!"
        hostname: "{{ ansible_hostname }}"
        state: domain
      register: domain_join_result

    - name: Reboot if necessary
      win_reboot:
      when: domain_join_result.reboot_required
