- name: Windows Setup # This ansible script will setup and deploy al windows boxes
  gather_facts: no
  hosts: localhost
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"  # Comes in handy later when sshing into a new box
  tasks:
    - name: Create Tortoise
      command: >
        openstack server create
        --flavor medium
        --image WinXP-SP5
        --boot-from-volume 100
        --nic net-id=abbf3cf1-3be6-4c07-9e0d-763336d4f66d
        --nic net-id=1f760c4b-02ee-4a27-bc95-aebc5cbae0e1,v4-fixed-ip="10.1.0.12"
        --user-data prepare-ansible-for-windows
        --key-name GrayTeam
        Tortoise
      ignore_errors: yes

    - name: Create IIS server
      command: >
        openstack server create
        --flavor medium
        --image Win10-21H2
        --boot-from-volume 100
        --nic net-id=abbf3cf1-3be6-4c07-9e0d-763336d4f66d
        --nic net-id=1f760c4b-02ee-4a27-bc95-aebc5cbae0e1,v4-fixed-ip="10.1.0.13"
        --user-data prepare-ansible-for-windows
        --key-name GrayTeam
        Monkey
      ignore_errors: yes
